block-beta
  columns 2

  application("Application layer"):2
  presentation("Presentation layer"):2
  session("Session layer"):2
  transport("Transport layer"):2
  network("Network layer"):2
  data("Data link layer"):2
  physical("Physical layer"):2

  style physical fill:#0ff
  style data fill:#0ee
  style network fill:#0dd
  style transport fill:#0cc
  style session fill:#0bb
  style presentation fill:#0aa
  style application fill:#099
