block-beta
  columns 2

  application("Application layer"):2
  presentation("Presentation layer"):2
  session("Session layer"):2
  transport("Transport layer"):2
  network("Network layer"):2
  data2("Data link layer"):2
  physical("Physical layer"):2

  style physical fill:#dff
  style network fill:#add
  style transport fill:#9cc
  style session fill:#8bb
  style presentation fill:#8aa
  style application fill:#899
  style data2 fill:#0ee
